name: Coverage Summary

on: pull_request

jobs:
  add_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: echo "``` txt\\n" > coverage.txt && yarn test >> coverage.txt && echo "```" >> coverage.txt

      - name: Comment PR
        uses: harupy/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: coverage.txt
